### ISSUE TITLE
Not Working on Newer Androids

### ISSUE THREAD

**Issue by mahdisml** [hexian000/CallRecorder#1]
Not Working on Newer Androids such as 9 , 8 , 7 :(

**Comment by hexian000** [comment]
Sorry for late reply...

It works on my phone. Tested on 9 & 10.
Have you installed it as a system app?

**Comment by mahdisml** [comment]
oh i didn't see it in README :)
i'm working a call recorder in regular app ( non system app ).

**Comment by hexian000** [comment]
As far as I know, there is no clean way to record phone calls as a non system app due to Android restrictions. Hope this helps :)
